Create zh_cn.json
Fuzss/horseexpert pull request #6
Opened 2023-08-19 04:55 UTC by Rad233

2023-08-20 14:58 UTC, nageih requested changes

2023-08-20 14:58 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.max": "最高：%s",
```suggestion
  "horse.tooltip.max": "最大：%s",
```

2023-08-20 14:58 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.max": "最高：%s",
这样感觉更顺口

2023-08-20 14:58 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.min": "最低：%s",
```suggestion
  "horse.tooltip.min": "最小：%s",
```

2023-08-20 14:58 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.strength": "运载能力：%s",
```suggestion
  "horse.tooltip.strength": "存储格数：%s",
```

2023-08-20 14:58 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.strength.unit": "%s单元格",
```suggestion
  "horse.tooltip.strength.unit": "%s个槽位",
```

2023-08-20 15:19 UTC, Rad233 commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.max": "最高：%s",
> 

对。虽然感觉“高”和“低”对于一个数据是正确的表达，但“大”和“小”应用更加广泛。

2023-08-20 15:24 UTC, Rad233 commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.strength": "运载能力：%s",
“载重量”如何？这是一个用于描述载重能力的词，能够体现坐骑的“strength”

2023-08-20 15:32 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.strength": "运载能力：%s",
我觉得不错，但是这样又和后面的%s个槽位对不上

2023-08-20 15:41 UTC, Rad233 commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.strength": "运载能力：%s",
“负重格数”如何？一方面能体现坐骑的主动运输能力，另一方面能对上“槽位”。要找到能对上槽位的词语应该不太可能，所以复合一下，造一个易懂的专有词语。wiki上对此似乎没有相关描述。

2023-08-21 00:10 UTC, nageih commented on 1.18/Forge/src/generated/resources/assets/horseexpert/lang/zh_cn.json
> +  "horse.tooltip.strength": "运载能力：%s",
我觉得不错

2023-08-21 09:13 UTC, nageih approved these changes

2023-11-06 19:30 UTC, Fuzss commented
Thanks!

2023-11-06 19:30 UTC, merged